name: github-repo-stats

on:
  schedule:
    # S'exécute une fois par jour vers la fin de la journée (en UTC)
    - cron: "0 23 * * *"
  workflow_dispatch: # Permet de l'exécuter manuellement

jobs:
  j1:
    name: github-repo-stats
    runs-on: ubuntu-latest
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          ghtoken: ${{ secrets.GHRS_GITHUB_API_TOKEN }}
          # Vos données iront directement dans votre nouveau dépôt privé
          datarepo: moimeme81/Datarepo
