name: Statistiques de trafic GitHub

on:
  schedule:
    # S'exécute tous les jours à 23h45 UTC
    - cron: "45 23 * * *"
  # Permet de lancer le script manuellement depuis l'interface
  workflow_dispatch:

jobs:
  run-ghrs:
    name: Générer le rapport de trafic
    runs-on: ubuntu-latest
    steps:
      - name: Lancer GitHub Repo Stats
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          # Le dépôt ciblé
          repository: ${{ github.repository }}
          # Le jeton secret que nous avons créé
          ghrs_github_api_token: ${{ secrets.GHRS_GITHUB_API_TOKEN }}
